# yaml-language-server: $schema=https://platen.io/schemas/config/schema.json
# Update to your own settings for URL/title
baseURL: https://poisoned-sweets.netlify.app/
title:   Poisoned Sweets

module:
  imports:
    - path: github.com/platenio/platen/modules/platen

menu:
  before:
    - name: About
      url:  /about
    - name: Categories
      url: /categories
    - name: Tags
      url: /tags

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true

params:
  description: A horror blog.
